TUẦN 3 : NUMPY, PANDAS, MATPLOTLIB
Pandas là một thư viện tương đối mới, được xây dựng dựa trên NumPy, và cung cấp một cách cài đặt hiệu quả cho cấu trúc dữ liệu DataFrame.

DataFrame về bản chất là các mảng đa chiều (multidimensional arrays) có gắn nhãn hàng (row labels) và nhãn cột (column labels), đồng thời thường chứa dữ liệu không đồng nhất về kiểu (heterogeneous types) và/hoặc giá trị bị thiếu (missing data).

Bằng việc cung cấp một giao diện lưu trữ thuận tiện cho dữ liệu có nhãn (labeled data), Pandas triển khai nhiều phép toán xử lý dữ liệu mạnh mẽ, quen thuộc với người dùng các hệ quản trị cơ sở dữ liệu (database frameworks) cũng như các chương trình bảng tính (spreadsheet programs).

Mặc dù cấu trúc dữ liệu ndarray của NumPy cung cấp các tính năng nền tảng quan trọng, nhưng những hạn chế của nó trở nên rõ ràng khi cần sự linh hoạt cao hơn, chẳng hạn như gắn nhãn cho dữ liệu, xử lý dữ liệu bị thiếu, v.v.

Pandas cung cấp khả năng truy cập và xử lý hiệu quả các tác vụ “data munging” (tiền xử lý, làm sạch và biến đổi dữ liệu) — những công việc chiếm phần lớn thời gian làm việc.

In [ ]:
import pandas as pd
pd.__version__

-----
Series

Pandas Series là một mảng một chiều (one-dimensional array) có chỉ mục (index).

Series có thể được khởi tạo từ một danh sách (list) hoặc một mảng (array) như sau:

Tạo Series từ list

Tạo Series từ list

In [28]:
data_pd = pd.Series([0.5, 0.3, 1.0, 2.5])
data_pd

0    0.5
1    0.3
2    1.0
3    2.5
dtype: float64

Tạo Series từ Numpy array

In [29]:
import numpy as np
S = 4
numpy_arr = np.arange(S)
data_pd = pd.Series(numpy_arr)
data_pd

0    0
1    1
2    2
3    3
dtype: int32

Attributes

In [23]:
data_pd.values

array([0, 1, 2, 3])

In [24]:
data_pd.index

RangeIndex(start=0, stop=4, step=1)

indexing

In [25]:
data_pd[1]

1

In [26]:
data_pd[-2:]

2    2
3    3
dtype: int32

In [27]:
data_pd[-1] #khong co chi so index = -1

KeyError: -1

letter indexing

In [32]:
#chi so nguyen kho ding => thu doi sang chu cai
data_pd = pd.Series([1.25,2.0,0.75,1.0], index = ['a','b','c','d'])

In [33]:
data_pd[-1]

1.0

In [34]:
data_pd['b']

2.0

BTVN1
Giải thích hiện tượng trên

Combined Indexing

In [55]:

index = ['a','b','c','d',3]
data_pd = pd.Series(numpy_arr, index=index)

In [56]:
data_pd['a']

0

In [57]:

data_pd[3]

4

panpas and dictionary

In [60]:
#he thong chi muc cua pandas co cau truc tuong tu Dictionary
#viec tao 1 doi tuong pandas tu Dictionary la dieu hoan toan de hieu
some_poppulation_dict = {'SaiGon' : 59,
                         'Dong Nai' : 60,
                         'Binh Thuan' : 86,
                         'Ha Noi' : 29}
data_pd = pd.Series(some_poppulation_dict)
data_pd['SaiGon']

59

In [61]:
#Pandas cung ho tro slising
#luu y : slising theo index label la "bao gom ca diem ket thuc"
data_pd['SaiGon':'Ha Noi']

SaiGon        59
Dong Nai      60
Binh Thuan    86
Ha Noi        29
dtype: int64

pandas and scalar

In [62]:
#du lieu co the la mot gia tri vo huong (scalar)
#va gia tri nay se duoc lap lai de dien vao toan bo index da chi dinh
data_pd = pd.Series(5, index=[2,3,8])
data_pd

2    5
3    5
8    5
dtype: int64

dataframe

DataFrame tương tự mảng 2 chiều, với index hàng và tên cột linh hoạt; về bản chất là tập hợp các Series được căn chỉnh theo index.

Tạo dataframe với 2 dict

In [69]:
some_poppulation_dict = {'SaiGon' : 5152,
                         'Dong Nai' : 6000,
                         'Binh Thuan' : 8386,
                         'Ha Noi' : 2979}
some_area_dict = {'SaiGon' : 51,
                         'Dong Nai' : 60,
                         'Binh Thuan' : 86,
                         'Ha Noi' : 29,
                         'Vung Tau':72}
state = pd.DataFrame({'Poppulation' :some_poppulation_dict,'Area' :some_area_dict})
state

            Poppulation  Area
SaiGon           5152.0    51
Dong Nai         6000.0    60
Binh Thuan       8386.0    86
Ha Noi           2979.0    29
Vung Tau            NaN    72

In [70]:
state['SaiGon': 'Ha Noi']

            Poppulation  Area
SaiGon           5152.0    51
Dong Nai         6000.0    60
Binh Thuan       8386.0    86
Ha Noi           2979.0    29

In [71]:
state['SaiGon': 'Ha Noi']['Poppulation']

SaiGon        5152.0
Dong Nai      6000.0
Binh Thuan    8386.0
Ha Noi        2979.0
Name: Poppulation, dtype: float64

In [72]:
state['Poppulation']['SaiGon': 'Ha Noi'] #khong quan trong thu tu

SaiGon        5152.0
Dong Nai      6000.0
Binh Thuan    8386.0
Ha Noi        2979.0
Name: Poppulation, dtype: float64

In [73]:
state['SaiGon': 'Ha Noi']['Poppulation']['Area'] #cot area khong ton tai

KeyError: 'Area'

In [74]:
state['Area']

SaiGon        51
Dong Nai      60
Binh Thuan    86
Ha Noi        29
Vung Tau      72
Name: Area, dtype: int64

In [75]:
state[:]['Area']

SaiGon        51
Dong Nai      60
Binh Thuan    86
Ha Noi        29
Vung Tau      72
Name: Area, dtype: int64

Attributes

In [76]:
state.index

Index(['SaiGon', 'Dong Nai', 'Binh Thuan', 'Ha Noi', 'Vung Tau'], dtype='object')

In [77]:
state.index[-1]

'Vung Tau'

In [78]:
state.columns

Index(['Poppulation', 'Area'], dtype='object')

In [79]:
state.columns[0:1]

Index(['Poppulation'], dtype='object')

Series indexing/slicing/fancy indexing

In [82]:
import pandas as pd
data = pd.Series([0.75,0.5,1.0,2.0],
                 index = ['a','b','c','d'])
data

a    0.75
b    0.50
c    1.00
d    2.00
dtype: float64

explicit vs implicit index

In [83]:
data['b']

0.5

In [84]:
data[-1]

2.0

In [85]:
data['a':'c']

a    0.75
b    0.50
c    1.00
dtype: float64

In [86]:
data[0:2]

a    0.75
b    0.50
dtype: float64

adding values

In [87]:
data['e'] = 10
data

a     0.75
b     0.50
c     1.00
d     2.00
e    10.00
dtype: float64

in

In [88]:
'a' in data

True

In [89]:
'f' in data

False

key()

In [90]:
data.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

items

In [91]:
list(data.items())

[('a', 0.75), ('b', 0.5), ('c', 1.0), ('d', 2.0), ('e', 10.0)]

values()

In [92]:
data.values

array([ 0.75,  0.5 ,  1.  ,  2.  , 10.  ])

masking

In [93]:
data[(data > 0.5) & (data <10)]

a    0.75
c    1.00
d    2.00
dtype: float64

fancy indexing

In [97]:
data[['a','e']]

a     0.75
e    10.00
dtype: float64